### ISSUE TITLE
requireNativeComponent: "RNCMasketView" was not found in the UI manager

### ISSUE THREAD

**Issue by thidasapankaja** [chramos/react-native-skeleton-placeholder#121]
This is a very useful library.

However I'm facing an issue running the app on Android. iOS works fine without any issue but Android crashes with this error `requireNativeComponent: "RNCMasketView" was not found in the UI manager`.

How can I get this fixed ?

**Comment by rpelorosso-sv** [comment]
Did you find a solution to this?

**Comment by thidasapankaja** [comment]
@rpelorosso-sv We're using monorepo for the project. So, my issue was I wasn't importing the library in the projects package.json. Importing that there fixed it.
And make sure you installed the dependencies mentioned
