### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'child.type.displayName')

### ISSUE THREAD

**Issue by mngyuan** [chramos/react-native-skeleton-placeholder#14]
Trying to integrate a minimal usage of this library into my app but it isn't working

```jsx
import SkeletonPlaceholder from 'react-native-skeleton-placeholder';

...

<>
  <SkeletonPlaceholder>
    <View>
      <Text>{name}</Text>
     </View>
  </SkeletonPlaceholder>
</>
```

Installed linear gradient, ran pod install, `package.json`:

```json
"react-native": "0.62.2",
"react-native-linear-gradient": "^2.5.6",
"react-native-skeleton-placeholder": "^2.0.7",
```

![Screen Shot 2020-08-24 at 4 29 36 PM](https://user-images.githubusercontent.com/3166481/91106290-23fb3480-e627-11ea-930e-7ff73ac9a5cc.png)

**Comment by chramos** [comment]
@mngyuan, you are trying to use it the wrong way. try something like this:
```js  
if(isLoading) {
   return (
   <SkeletonPlaceholder>
      <SkeletonPlaceholder.Item width={100} height={16}  />
   </SkeletonPlaceholder>
   )
}

return (
   <View>
      <Text>{name}</Text>
   </View>
)
```

**Comment by chramos** [comment]
the library doesn't automatically transform your layout into placeholder. you should create it

**Comment by mngyuan** [comment]
gotcha, makes sense, ended up rolling my own solution

**Comment by pranavahir** [comment]
Can We Use it in _renderItem?
