### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by ydang204** [chramos/react-native-skeleton-placeholder#16]
Does this project support typescript? I'm using TS in my project and feel happy to integrate this library
![image](https://user-images.githubusercontent.com/31928624/96294572-c5df4200-1016-11eb-9ff4-5356b5c1892b.png)

**Comment by chramos** [comment]
Hey @ydang204 .. weird, this library supports Typescript.. I'll take a look and fix it up if needed

**Comment by bjakubowiak-oanda** [comment]
Hey. Any updates on this task? Do you need a hand solving the issue?

**Comment by chramos** [comment]
@ydang204 @bjakubowiak-oanda the issue has been solved
please update to latest version and check it up.

let me know if everything is ok to close this issue

**Comment by bjakubowiak-oanda** [comment]
Still getting the same error as @ydang204 posted

**Comment by chramos** [comment]
try again please. version 2.0.11

**Comment by bjakubowiak-oanda** [comment]
Looks good, thanks for getting this sorted so quickly!

**Comment by chramos** [comment]
No problem. I’ll close this issue. If you have another problem please open a new one.

**Comment by ydang204** [comment]
Thank you very much @chramos :D
