### ISSUE TITLE
Overlap when placed horizontally (row view)

### ISSUE THREAD

**Issue by ArietNyshanbaev** [chramos/react-native-skeleton-placeholder#18]
First of all I want to thank you for this amazing library which is really easy to use.
We are having trouble when we layout placeholders horizontally, if we place placeholders in flexDirection: row based View, there we got some problem regarding rendering of placeholders it is kind of overlapping .
Thanks in advance.

**Comment by chramos** [comment]
Hey @ArietNyshanbaev can you show me how to reproduce the issue?

**Comment by t4dek** [comment]
Hi! I came across the same issue
Here is sample code to reproduce:

```
          <View style={styles.skeletonLabelContainer}>
            <Text style={styles.label}>Hello</Text>
            <SkeletonPlaceholder>
              <View style={styles.skeletonItem} />
            </SkeletonPlaceholder>
          </View>

  skeletonLabelContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  label: {
    fontSize: 15,
    lineHeight: 20,
  },
  skeletonItem: {
    height: 20,
    width: 150,
  },
```

**Comment by chramos** [comment]
thanks @t4dek, I'll check it and solve ASAP

**Comment by chramos** [comment]
Hey guys, check the latest version 3.0.2 and let me know if the issue has been solved.

**Comment by chramos** [comment]
Someone can check if the issue has been solved?

**Comment by t4dek** [comment]
@chramos hey!
Fix worked, thx!

**Comment by chramos** [comment]
Thanks for the feedback!
