### ISSUE TITLE
Animation doesn't start with flex

### ISSUE THREAD

**Issue by Hugogsalas** [chramos/react-native-skeleton-placeholder#19]
When I put flex in childrens styles, the animation doesn't start

**Comment by chramos** [comment]
@Hugogsalas please, add an example to reproduce the issue.

**Comment by chramos** [comment]
@Hugogsalas try to update your library to the latest version. we had the same issue in the past but it already solved

**Comment by chramos** [comment]
I'm closing this issue due inactivity
