### ISSUE TITLE
componentWillUnmount() is deprecated

### ISSUE THREAD

**Issue by itsam** [chramos/react-native-skeleton-placeholder#2]
Hello, thanks for your effort!
Clean barebone code. Any plans to replace componentWillUnmount method?
Best.

**Comment by chramos** [comment]
Hey @itsam, thank you!
Sure, I'll publish a new version using hooks.

**Comment by chramos** [comment]
@itsam  A new version was been published.

**Comment by itsam** [comment]
@chramos Thank you :)
