### ISSUE TITLE
This library is not compatible with 'react-navigation'

### ISSUE THREAD

**Issue by kasim444** [chramos/react-native-skeleton-placeholder#20]
Hello everyone. First of all thank you for this library. I would like to share with you a little problem I have experienced. I wanted to share this with you, as there may be people like me who come across this problem.

I used to use 'react-navigation' library in an application I was developing. Later, I came across the react-native-skeleton-placeholder library to put a placeholder while in standby for dynamic data, and I continued to develop my application using the ios side. However, when I wanted to test the android side of the application in the future, I encountered an error like 'Task: app: mergeDexDebug FAILED'. It took me quite a bit of time to figure this out. I finally discovered that the problem caused a problem on the android side when we installed '@ react-native-masked-view / masked-view' to use this library with the library '@ react-native-community / masked-view' to use react-navigation. 

So if you use react-navigation in your application, I recommend that you do not use this library. While there is no problem on the iOS side, the application will give an error on the android side. If you add this information to the main 'README.md' file of the application, it will be very helpful to developers who have this problem like me. Otherwise, they will spend a lot of time exploring this problem.

I wish you a good day.

**Comment by suhail135** [comment]
@kasim444 you just saved me

**Comment by sallar** [comment]
I sent a PR to update the dependency in README. The actual code just works.

**Comment by chramos** [comment]
@kasim444 , thx for the feedback

**Comment by chramos** [comment]
I'll solve it ASAP

**Comment by chramos** [comment]
@kasim444. the problem is I forgot to update the installation instruction in README. The library does not use the `@react-native-masked-view/masked-view` anymore. The right dependency is the `@react-native-community/masked-view` "the same react-navigation dependency". To get it work remove you should remove `@react-native-masked-view/masked-view` from your project.

**Comment by chramos** [comment]
@sallar thank you for the PR. It was merged

**Comment by sallar** [comment]
Thanks!

**Comment by kasim444** [comment]
The problem has been resolved. Thanks for your support.
