### ISSUE TITLE
Masked view dependency has changed it's name causing error

### ISSUE THREAD

**Issue by TowhidKashem** [chramos/react-native-skeleton-placeholder#22]
Recently react native community packages began to change their names and masked view is one of them:

https://github.com/react-native-masked-view/masked-view

It's now to be installed as:

`@react-native-masked-view/masked-view`

but in the dependencies and peer dependencies properties in this libraries package.json, it's listed under the old name:

`@react-native-community/masked-view`

Could we update this? I would open a PR but I'm not to familiar with dependency management and not sure if simply adding the new name in addition to the old is enough or if it's more complicated than that..

**Comment by TowhidKashem** [comment]
Sorry this was a false alarm, closing this. `@react-native-community/masked-view` works fine under the old name.

**Comment by sophie-li** [comment]
I was wondering if you encountered this error on v4.0.0? @TowhidKashem 
https://github.com/chramos/react-native-skeleton-placeholder/issues/41
