### ISSUE TITLE
Poor Performance

### ISSUE THREAD

**Issue by tcorreiaubi** [chramos/react-native-skeleton-placeholder#23]
I'm having some really poor performance using react-native-skeleton-placeholder, I'm not sure if it's me who is doing something wrong, or even my mobile phone, but I made a sample project, if you can give it a look. (https://github.com/tcorreiaubi/placeholderPerformance)

With the current code I'm having between 7-15fps which is really low since I would expect something around 60.
Thanks in advance for the amazing work you did with the package, really simple of using.

**Comment by chramos** [comment]
hey @tcorreiaubi, thank you for the feedback. It's a important point.
Could you try it in release mode to check if the performance is low as well?

**Comment by tcorreiaubi** [comment]
Hey @chramos sadly I had the same issues in a release build, I only tested on android, but I believe the behavior also occurs on iOS

**Comment by chramos** [comment]
Ok @tcorreiaubi, I'll check and try to fix it up ASAP. thanks again

**Comment by chramos** [comment]
@tcorreiaubi after some research I found the problem. Its related to masked-view:
https://github.com/react-native-masked-view/masked-view/issues/88

in iOS its working smoothly in 60FPS.
unfortunately I don't have much free time to continue investigating to try to find a solution for that.

**Comment by tcorreiaubi** [comment]
Hey @chramos, thank you so much for the time you invested debugging it, I will try to find sometime to help this or next week, and If I come to a conclusion will let you know

**Comment by chramos** [comment]
@tcorreiaubi thank you 👍 
any help will be appreciated

**Comment by tcorreiaubi** [comment]
@chramos I was looking at the issue and seems that someone has a pull request to fix it on the masked view side(https://github.com/react-native-masked-view/masked-view/pull/98) I will close the issue here, thanks for all the help and time
