### ISSUE TITLE
Something is wrong/strange with the latest version

### ISSUE THREAD

**Issue by umang-simform** [chramos/react-native-skeleton-placeholder#25]
We recently upgraded to 3.0.2 from 2.0.11 and it seems something is definitely changed in not so good way,
So first check the video with the old version: 

https://user-images.githubusercontent.com/61829970/107612046-5f3bff00-6c6b-11eb-9346-19c780614129.mov
Now check the new one, Code is the exact the same only change we have made is to update the version in package.json
https://user-images.githubusercontent.com/61829970/107612090-7a0e7380-6c6b-11eb-93a1-0d4ddf2f7e05.mp4

Please let us know if anything needs to be changed within the code to overcome this?

**Comment by chramos** [comment]
Hi @umang-simform, the video using the latest version have a weird behavior
please can you provide an example of how are you using it in your code?

**Comment by chramos** [comment]
@umang-simform the issue happens when you use colors with alpha value in the **backgroundColor** or **highlightColor** prop

check the example bellow
```js
const App = () => {
  return (
    <View
      style={{
        backgroundColor: "#131413",
        justifyContent: "center",
        alignItems: "center",
        flex: 1
      }}>
      <SkeletonPlaceholder 
        backgroundColor="#2f3230" //TRY ADD rgba(255, 255, 255, 0.3) to see the difference
        highlightColor="#656966" //TRY ADD rgba(255, 255, 255, 0.6) to see the difference
        >
        <SkeletonPlaceholder.Item flexDirection="row" alignItems="center">
          <SkeletonPlaceholder.Item width={64} height={64} borderRadius={50} />
          <SkeletonPlaceholder.Item marginLeft={16}>
            <SkeletonPlaceholder.Item
              width={200}
              height={20}
              borderRadius={4}
            />
            <SkeletonPlaceholder.Item
              marginTop={8}
              width={300}
              height={20}
              borderRadius={4}
            />
            <SkeletonPlaceholder.Item
              marginTop={8}
              width={260}
              height={20}
              borderRadius={4}
            />
          </SkeletonPlaceholder.Item>
        </SkeletonPlaceholder.Item>
        <SkeletonPlaceholder.Item
          marginTop={32}
          flexDirection="row"
          alignItems="center">
          <SkeletonPlaceholder.Item width={64} height={64} borderRadius={50} />
          <SkeletonPlaceholder.Item marginLeft={16}>
            <SkeletonPlaceholder.Item
              width={200}
              height={20}
              borderRadius={4}
            />
            <SkeletonPlaceholder.Item
              marginTop={8}
              width={300}
              height={20}
              borderRadius={4}
            />
            <SkeletonPlaceholder.Item
              marginTop={8}
              width={260}
              height={20}
              borderRadius={4}
            />
          </SkeletonPlaceholder.Item>
        </SkeletonPlaceholder.Item>
      </SkeletonPlaceholder>
    </View>
  );
};
```

**Comment by umang-simform** [comment]
> @umang-simform the issue happens when you use colors with alpha value in the **backgroundColor** or **highlightColor** prop
> 
> check the example bellow
> 
> ```js
> const App = () => {
>   return (
>     <View
>       style={{
>         backgroundColor: "#131413",
>         justifyContent: "center",
>         alignItems: "center",
>         flex: 1
>       }}>
>       <SkeletonPlaceholder 
>         backgroundColor="#2f3230" //TRY ADD rgba(255, 255, 255, 0.3) to see the difference
>         highlightColor="#656966" //TRY ADD rgba(255, 255, 255, 0.6) to see the difference
>         >
>         <SkeletonPlaceholder.Item flexDirection="row" alignItems="center">
>           <SkeletonPlaceholder.Item width={64} height={64} borderRadius={50} />
>           <SkeletonPlaceholder.Item marginLeft={16}>
>             <SkeletonPlaceholder.Item
>               width={200}
>               height={20}
>               borderRadius={4}
>             />
>             <SkeletonPlaceholder.Item
>               marginTop={8}
>               width={300}
>               height={20}
>               borderRadius={4}
>             />
>             <SkeletonPlaceholder.Item
>               marginTop={8}
>               width={260}
>               height={20}
>               borderRadius={4}
>             />
>           </SkeletonPlaceholder.Item>
>         </SkeletonPlaceholder.Item>
>         <SkeletonPlaceholder.Item
>           marginTop={32}
>           flexDirection="row"
>           alignItems="center">
>           <SkeletonPlaceholder.Item width={64} height={64} borderRadius={50} />
>           <SkeletonPlaceholder.Item marginLeft={16}>
>             <SkeletonPlaceholder.Item
>               width={200}
>               height={20}
>               borderRadius={4}
>             />
>             <SkeletonPlaceholder.Item
>               marginTop={8}
>               width={300}
>               height={20}
>               borderRadius={4}
>             />
>             <SkeletonPlaceholder.Item
>               marginTop={8}
>               width={260}
>               height={20}
>               borderRadius={4}
>             />
>           </SkeletonPlaceholder.Item>
>         </SkeletonPlaceholder.Item>
>       </SkeletonPlaceholder>
>     </View>
>   );
> };
> ```

Thanks for the explanation but I am still confused why it is not causing any issue with the previous version?
Also here is the code we have in our app:
```
const SkeletonItem = () => {
  return (
    <SkeletonPlaceholder
      backgroundColor={Colors.primary10opacity}
      highlightColor={Colors.primary20opacity}
      speed={2000}
    >
      <View style={styles.lineStyle} />
      <View style={styles.viewContainer}>
        <View style={{ width: scale(50), height: scale(50), borderRadius: scale(25) }} />
        <View style={{ marginLeft: scale(9) }}>
          <View style={styles.nameTimeStyle}>
            <View style={styles.nameText} />
            <View style={styles.timeText} />
          </View>
          <View style={styles.transcriptMain} />
          <View style={styles.transcriptText} />
        </View>
      </View>
      <View style={styles.lineBottom} />
    </SkeletonPlaceholder>
  );
};

const SkeletonView = ({ numberOfItem = 1 }) => {
  let items = [];
  for (let i = 0; i < numberOfItem; i++) {
    items.push(<SkeletonItem key={i} />);
  }
  return <View>{items}</View>;
};
```

**Comment by chramos** [comment]
Previous version is totally different from the current 3.x.x. it was changed to react-native-masked-view

**Comment by umang-simform** [comment]
Got it, Thanks for the clarification

**Comment by chramos** [comment]
Closing issue

**Comment by janandaraj** [comment]
> @umang-simform the issue happens when you use colors with alpha value in the **backgroundColor** or **highlightColor** prop
> 
> check the example bellow
> 
> ```js
> const App = () => {
>   return (
>     <View
>       style={{
>         backgroundColor: "#131413",
>         justifyContent: "center",
>         alignItems: "center",
>         flex: 1
>       }}>
>       <SkeletonPlaceholder 
>         backgroundColor="#2f3230" //TRY ADD rgba(255, 255, 255, 0.3) to see the difference
>         highlightColor="#656966" //TRY ADD rgba(255, 255, 255, 0.6) to see the difference
>         >
>         <SkeletonPlaceholder.Item flexDirection="row" alignItems="center">
>           <SkeletonPlaceholder.Item width={64} height={64} borderRadius={50} />
>           <SkeletonPlaceholder.Item marginLeft={16}>
>             <SkeletonPlaceholder.Item
>               width={200}
>               height={20}
>               borderRadius={4}
>             />
>             <SkeletonPlaceholder.Item
>               marginTop={8}
>               width={300}
>               height={20}
>               borderRadius={4}
>             />
>             <SkeletonPlaceholder.Item
>               marginTop={8}
>               width={260}
>               height={20}
>               borderRadius={4}
>             />
>           </SkeletonPlaceholder.Item>
>         </SkeletonPlaceholder.Item>
>         <SkeletonPlaceholder.Item
>           marginTop={32}
>           flexDirection="row"
>           alignItems="center">
>           <SkeletonPlaceholder.Item width={64} height={64} borderRadius={50} />
>           <SkeletonPlaceholder.Item marginLeft={16}>
>             <SkeletonPlaceholder.Item
>               width={200}
>               height={20}
>               borderRadius={4}
>             />
>             <SkeletonPlaceholder.Item
>               marginTop={8}
>               width={300}
>               height={20}
>               borderRadius={4}
>             />
>             <SkeletonPlaceholder.Item
>               marginTop={8}
>               width={260}
>               height={20}
>               borderRadius={4}
>             />
>           </SkeletonPlaceholder.Item>
>         </SkeletonPlaceholder.Item>
>       </SkeletonPlaceholder>
>     </View>
>   );
> };
> ```

is it fixed? it's a bug right? i'm facing the same
