### ISSUE TITLE
Please make new NPM release of this library

### ISSUE THREAD

**Issue by wojciechkrol** [chramos/react-native-skeleton-placeholder#26]
Hello,

Latest changes have been pushed long time ago and there is still no NPM release of this library. Recent commit brings important change of used `masked-view` library. Right now we have project based on react-navigation and we can't use your library because `@react-native-masked-view/masked-view` collides with `@react-native-community/masked-view`.

**Comment by chramos** [comment]
Hello @wojciechkrol , I'll check it up

**Comment by chramos** [comment]
it's done!

**Comment by wojciechkrol** [comment]
Thank you! Now it works 👍🏻
