### ISSUE TITLE
lib directory does not exist in 3.0.3

### ISSUE THREAD

**Issue by isnifer** [chramos/react-native-skeleton-placeholder#27]
![image](https://user-images.githubusercontent.com/1788245/108134768-d89e7c00-70c7-11eb-98f6-47f9ff24c126.png)

**Comment by chramos** [comment]
Wow, I'll fix it ASAP and let you know

**Comment by chramos** [comment]
@isnifer, I published a new version **3.0.4**.
please check it out

**Comment by kovetskiy** [comment]
Can confirm, it works fine on 3.0.4 :+1:
