### ISSUE TITLE
3.0.3 - /node_modules/react-native-skeleton-placeholder/lib/SkeletonPlaceholder.js doesn't exist

### ISSUE THREAD

**Issue by ejsunrise** [chramos/react-native-skeleton-placeholder#28]
Error: While trying to resolve module `react-native-skeleton-placeholder` from file `/Card/SkeletonCard.js`, the package `/node_modules/react-native-skeleton-placeholder/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/node_modules/react-native-skeleton-placeholder/lib/SkeletonPlaceholder.js`. Indeed, none of these files exist:

  * /node_modules/react-native-skeleton-placeholder/lib/SkeletonPlaceholder.js(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * /node_modules/react-native-skeleton-placeholder/lib/SkeletonPlaceholder.js/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
    at DependencyGraph.resolveDependency (/node_modules/metro/src/node-haste/DependencyGraph.js:376:17)

**Comment by kovetskiy** [comment]
Same issue for me. I guess it's also the same as #27 

Downgrading to 3.0.2 solved the issue for me.

**Comment by chramos** [comment]
fixed https://github.com/chramos/react-native-skeleton-placeholder/issues/27#issuecomment-780427708.
thank you for the feedback guys!!

**Comment by ejsunrise** [comment]
Thanks for the fix @chramos
