### ISSUE TITLE
Speed Issue

### ISSUE THREAD

**Issue by heavell7870** [chramos/react-native-skeleton-placeholder#29]
When I mentioned speed = {400} in 
`<SkeletonPlaceholder speed = {400} backgroundColor = '#1e1e1e'  highlightColor='#6060600'>`
animation stopped working, even after re installing in my physical device its not working

my code 

`if (loading) {
      return (
      <View style = {{height:'100%', backgroundColor:'black'}}>
          <SkeletonPlaceholder backgroundColor = '#1e1e1e' highlightColor='#6060600'>
          <View style = {{height:150, width:'94%', marginHorizontal:'3%', marginTop: 10, borderRadius: 10}} />
          <View style = {{height:150, width:'94%', marginHorizontal:'3%', marginTop: 10, borderRadius: 10}} />
          <View style = {{height:150, width:'94%', marginHorizontal:'3%', marginTop: 10, borderRadius: 10}} />
          <View style = {{height:150, width:'94%', marginHorizontal:'3%', marginTop: 10, borderRadius: 10}} />
        </SkeletonPlaceholder>
        </View>
        
      );
    }`

please help me
@chramos

**Comment by chramos** [comment]
hey @heavell7870 
I'll check it up

**Comment by heavell7870** [comment]
> hey @heavell7870
> I'll check it up

Thank you

**Comment by heavell7870** [comment]
issue fixed actually there was no issue with this it was a type error I wrote #6060600  instead of #606060
