### ISSUE TITLE
Feature request: Static/non-animated mode

### ISSUE THREAD

**Issue by andreialecu** [chramos/react-native-skeleton-placeholder#38]
It would be great to be able to toggle animation via a property. 

The use case is that for a network error I'd like to keep displaying the placeholder and a retry button, but without the animation.

Something like:

```tsx
<SkeletonPlaceholder animate={!hasError}>
  ...
</SkeletonPlaceholder>
```

**Comment by chramos** [comment]
hey @andreialecu, good idea... I'll try to do it when I get some free time, or if you wanna try and open a PR ..feel free

**Comment by henaharon** [comment]
hey @chramos  how can we open a pr if lib is ignored ?
