### ISSUE TITLE
The animation does not work

### ISSUE THREAD

**Issue by HaffASE** [chramos/react-native-skeleton-placeholder#4]
If you use a component inside any component with useEffect, the animation does not work.

function ExampleComponent() {
useEffect(() => {}, []) // any effect

return (
  SkeletonPlaceholder
...
SkeletonPlaceholder
  )
}

"react": "16.9.0",
"react-native": "0.61.5",
"react-native-linear-gradient": "2.5.6",
"react-native-skeleton-placeholder": "2.0.1"

**Comment by claudiozam** [comment]
Hi, i have a similar issue with  "react-navigation": "^4.1.0".

If i call this.props.navigation.setParams({.......});  The animation does not work.

**Comment by chramos** [comment]
Thank you for feedback i'll check it out

**Comment by chramos** [comment]
@HaffASE  I published a new version that contains the animation fix. Try it and let me know if it works correctly

**Comment by chramos** [comment]
Closing the issue for not having a feedback
