### ISSUE TITLE
The animation does not work with react-navigation

### ISSUE THREAD

**Issue by claudiozam** [chramos/react-native-skeleton-placeholder#5]
If I call this.props.navigation.setParams({.......}); The animation does not work.

```
componentDidMount() {
    ......
    // Show the skeleton-placeholder
    ......
    this.props.navigation.setParams({changeFilter: 'all'});
    .....
}
```

"react": "16.9.0",
"react-native": "0.61.5",
"react-navigation": "^4.1.0".
"react-native-linear-gradient": "2.5.6",
"react-native-skeleton-placeholder": "2.0.1"

Thanks

**Comment by chramos** [comment]
Hi @claudiozam, I'll checkout it out, thanks for feedback

**Comment by chramos** [comment]
@claudiozam Please, check it out the new published version!

**Comment by mehdihussain9** [comment]
@chramos , Hi, is this work for android??

**Comment by chramos** [comment]
@mehdihussain9 Hi, yep!

**Comment by chramos** [comment]
Closing the issue for not having a feedback
