### ISSUE TITLE
Feature request: No option for changing left-right animation to right-left.

### ISSUE THREAD

**Issue by henaharon** [chramos/react-native-skeleton-placeholder#53]
In this function
const translateX = React.useMemo(() => animatedValue.interpolate({
        inputRange: [0, 1],
        **outputRange: [SCREEN_WIDTH, -SCREEN_WIDTH],**
    }), [animatedValue]);

can you guys add an option for switching the direction of the animation ? 

 --->>>        **outputRange: [-SCREEN_WIDTH, SCREEN_WIDTH],**
         
 thanks!
Jen.

**Comment by andreialecu** [comment]
I added this to #54

**Comment by henaharon** [comment]
@andreialecu Thank you!!
Is there a way i can get a notification if the branch will merged ?

**Comment by andreialecu** [comment]
You can try the PR before it's merged and published by modifying your `package.json` to reference the git branch directly:

```
"react-native-skeleton-placeholder": "https://github.com/andreialecu/react-native-skeleton-placeholder.git#updates",
```

This should work with yarn, I think it works with npm too. Make sure to run an install afterwards. 

Also you'll need to install `react-native-linear-gradient`, which is a dependency in that PR. See the PR text for further explanations.

**Comment by henaharon** [comment]
@andreialecu ok! tnx i will try.
