### ISSUE TITLE
Masked View conflict at version 5.0.0

### ISSUE THREAD

**Issue by ugrdursun** [chramos/react-native-skeleton-placeholder#64]
Hello, v4.0.0 is working fine (With no errors but lots of delay) with this:

    "@react-native-community/masked-view": "^0.1.11",

But v5.0.0 requires  **@react-native-masked-view/masked-view**. 

Problem: 

These two libraries are not working together. App is just not opening with console output below. (Stuck at splash screen).

`BugReporting extraData: {"AppRegistry.runApplication1": "Running \"AppName\" with {\"rootTag\":1,\"initialProps\":{}}"}`

If I uninstall **@react-native-community/masked-view**, tons of libraries depend on this library so its kinda not possible.

Do you have any suggestion ? Like how to make v5 work with community masked view?

**Comment by Sargnec** [comment]
open react-native-skeleton-placeholder in node-modules folder and go to lib > SkeletonPlaceholder.js 
change your masked_view_1 to this
`const masked_view_1 = __importDefault(require("@react-native-community/masked-view"));`

**Comment by rabie-khlifi** [comment]
its till a problem react @react-native-community/masked-view and  @react-native-masked-view/masked-view kinda have same name creates coflicts and @react-native-community/masked-view is needed for react navigations so i dont know why not use @react-native-community/masked-view like in v4 to prevent this conflict

**Comment by brunomartinezciompi** [comment]
Why this issue is closed? Changing something on node_modules should not be a proper solution!
