### ISSUE TITLE
[question] react-native-community/masked-view is deprecated 

### ISSUE THREAD

**Issue by emauricio** [chramos/react-native-skeleton-placeholder#85]
`"@react-native-community/masked-view": "^0.1.11",` 
<img width="717" alt="image" src="https://user-images.githubusercontent.com/7945345/193976713-02f1bfa8-a871-4cf7-8c9b-9aef022791aa.png">

why changed back to that one on the latest version?

thx

**Comment by chrismerino** [comment]
Exactly, the package "@react-native-community/masked-view" is deprecated.

**Comment by efstathiosntonas** [comment]
patch to use the `@react-native-masked-view/masked-view` instead of the community one:


`react-native-skeleton-placeholder+5.2.0.patch`

```patch
diff --git a/node_modules/react-native-skeleton-placeholder/lib/SkeletonPlaceholder.js b/node_modules/react-native-skeleton-placeholder/lib/SkeletonPlaceholder.js
index 314a93a..90f5a5a 100644
--- a/node_modules/react-native-skeleton-placeholder/lib/SkeletonPlaceholder.js
+++ b/node_modules/react-native-skeleton-placeholder/lib/SkeletonPlaceholder.js
@@ -33,7 +33,7 @@ var __importDefault = (this && this.__importDefault) || function (mod) {
     return (mod && mod.__esModule) ? mod : { "default": mod };
 };
 Object.defineProperty(exports, "__esModule", { value: true });
-const masked_view_1 = __importDefault(require("@react-native-community/masked-view"));
+const masked_view_1 = __importDefault(require("@react-native-masked-view/masked-view"));
 const React = __importStar(require("react"));
 const react_native_1 = require("react-native");
 const react_native_linear_gradient_1 = __importDefault(require("react-native-linear-gradient"));
```

**Comment by FelipeLimaDeSouza** [comment]
@emauricio 
I added "sed" in postinstall:

`"postinstall": "./scripts/replace.sh"`

In replace.sh:

`sed -i '' 's/react-native-community/react-native-masked-view/g' node_modules/react-native-skeleton-placeholder/lib/SkeletonPlaceholder.js`

**Comment by chramos** [comment]
oh, that's true!
I hadn't noticed that react-native-masked-view/masked-view was deprecated
I'll solve this issue ASAP

thank you guys

**Comment by manoj-jar** [comment]
hey @chramos any update on this ?

**Comment by chramos** [comment]
yes, it is fixed and I'll deploy a new version today
https://github.com/chramos/react-native-skeleton-placeholder/pull/91/files

**Comment by nickolasmdasilva** [comment]
@chramos  Is the new release available? Thank you
