### ISSUE TITLE
Support for `rgba()` colors in `highlightColor`

### ISSUE THREAD

**Issue by kevinhikaruevans** [chramos/react-native-skeleton-placeholder#88]
I'm currently using react-native-paper, which has colors provided by the theme. The default theme uses `rgba()` colors instead of hex. 

When an `rgba()` color is used, it returns an "Unsupported color format" error:

![image](https://user-images.githubusercontent.com/4730591/194624184-3bb65082-972f-4de0-b0ab-e8ec0ccc1e74.png)

This only happens with `highlightColor` and not `backgroundColor`, something like this fails:

```js
<SkeletonPlaceholder
  backgroundColor={colors.secondary}
  highlightColor={colors.secondaryContainer}
  borderRadius={4}
>
```

**Comment by chramos** [comment]
I agree, it is important to support rgba and hex
I'll check
