### ISSUE TITLE
Replace masked-view with the proper dependency 

### ISSUE THREAD

**Issue by valdirunars** [chramos/react-native-skeleton-placeholder#93]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-skeleton-placeholder@5.2.0` for the project I'm working on.

My issue was that there is an outdated dependency @react-native-community/masked-view that is conflicting with the entire communiy's usage of MaskedView. Please change to use the new namespace : @react-native-masked-view/masked-view

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-skeleton-placeholder/lib/SkeletonPlaceholder.js b/node_modules/react-native-skeleton-placeholder/lib/SkeletonPlaceholder.js
index 314a93a..9fdd651 100644
--- a/node_modules/react-native-skeleton-placeholder/lib/SkeletonPlaceholder.js
+++ b/node_modules/react-native-skeleton-placeholder/lib/SkeletonPlaceholder.js
@@ -33,7 +33,7 @@ var __importDefault = (this && this.__importDefault) || function (mod) {
     return (mod && mod.__esModule) ? mod : { "default": mod };
 };
 Object.defineProperty(exports, "__esModule", { value: true });
-const masked_view_1 = __importDefault(require("@react-native-community/masked-view"));
+const masked_view_1 = __importDefault(require("@react-native-masked-view/masked-view"));
 const React = __importStar(require("react"));
 const react_native_1 = require("react-native");
 const react_native_linear_gradient_1 = __importDefault(require("react-native-linear-gradient"));
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by chramos** [comment]
hey, fixed!
https://github.com/chramos/react-native-skeleton-placeholder/pull/91/files
